[package]
name = "gemini"
version = "0.1.0"
authors = ["Jacob Alexander <haata@kiibohd.com>", "Zion Koyl <hiszd1@gmail.com>"]
edition = "2021"
description = "Hexgears Gemini Dusk/Dawn Keyboard"
keywords = ["arm", "cortex-m", "atsam4", "atsam4s", "atsam4s8b", "hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kiibohd/kiibohd-firmware"

[lib]
path = "src/lib.rs"

[[bin]]
name = "gemini"
path = "src/bin.rs"

[dependencies]
const_env = "0.1"
cortex-m = "0.7"
cortex-m-rt = { version = "0.7" }
cortex-m-rtic = "1.0.0"
defmt = "0.3"
defmt-rtt = "0.3"
embedded-hal = "0.2.7"
heapless = "0.7"
kiibohd-hid-io = { version = "0.1" }
kiibohd-keyscanning = { version = "0.1", features = ["kll-core"] }
kiibohd-usb = { version = "0.1", default-features = false, features = ["hidio", "defmt-default", "kll-core"] }
kll-core = { version = "0.1" }
nb = "~0.1"
panic-probe = { version = "0.3", features = ["print-defmt"] }
paste = "1.0"

[dependencies.atsam4-hal]
git = "https://github.com/haata/atsam4-hal.git"
version = "0.1.15"
default-features = false
features = ["atsam4s8b", "usb", "defmt-default"]

[build-dependencies]
dotenv = "0.15"
kll-compiler = { version = "0.1" }
vergen = { version = "7.2", default-features = false, features = ["git"] }

[features]
default = [
    "defmt-default",
]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
