[tasks.bin]
command = "cargo"
args = ["objcopy", "--target", "thumbv7em-none-eabi", "--release", "--", "-O", "binary", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}.dfu.bin"]

[tasks.bin-dfu]
command = "dfu-suffix"
args = ["--add", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}.dfu.bin", "--vid", "${BOOT_VID}", "--pid", "${BOOT_PID}"]
dependencies = ["bin"]

[tasks.build]
command = "cargo"
args = ["bb"]

[tasks.build-release]
command = "cargo"
args = ["brb"]

[tasks.clippy]
command = "cargo"
args = ["clippyb", "--", "-D", "warnings"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "-Dwarnings" }
command = "cargo"
args = ["doc"]

[tasks.flash]
command = "dfu-util"
args = ["--alt", "0", "--download", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}.dfu.bin"]
dependencies = ["bin-dfu"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.gdb-server]
command = "cargo"
args = ["xtask", "gdb-server"]

[tasks.gdb-client]
command = "cargo"
args = ["xtask", "gdb-client"]

[tasks.run]
command = "cargo"
args = ["rb"]

[tasks.run-release]
command = "cargo"
args = ["rrb"]

[tasks.sanity]
dependencies = [
    "check",
    "clippy",
    "doc",
    "fmt-check",
]
